# Generated by Django 2.2.1 on 2019-06-24 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTokenInfo',
            fields=[
                ('id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=1000)),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='music.User')),
            ],
        ),
    ]
