# Generated by Django 2.2.1 on 2019-06-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_usertokeninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokeninfo',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
