# Generated by Django 2.2.1 on 2019-06-24 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20190624_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertokeninfo',
            name='userType',
            field=models.BooleanField(default=1),
        ),
    ]
