# Generated by Django 2.2.1 on 2019-06-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_usertokeninfo_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokeninfo',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
