# Generated by Django 2.2.1 on 2019-06-25 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20190625_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokeninfo',
            name='userType',
            field=models.IntegerField(default=1),
        ),
    ]
