# Generated by Django 2.2.1 on 2019-06-25 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20190625_0702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertokeninfo',
            old_name='userType',
            new_name='tokenType',
        ),
    ]
