# Generated by Django 2.2.1 on 2019-06-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20190625_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertokeninfo',
            name='userID',
            field=models.IntegerField(),
        ),
    ]
